Improving documentation
tawnkramer/sdsandbox pull request #85
Opened 2022-02-01 12:41 UTC by ebadi

2022-02-01 23:12 UTC, Maximellerbach requested changes
Requires some small changes before merging, but overall it's great. Thanks for taking the time for those corrections/improvement !

2022-02-01 23:12 UTC, Maximellerbach commented on docs/guide/create_a_track.md
> +3) Right click on the prefab and select "Unpack Prefab" (Unpack -> unpack completely), this will disociate the object in your scene from the Prefab stored in "Assets/Scenes/".
The issue behind unpacking everything is that if you change a given sub-prefab in the scenePrefab (for instance the RaceCanvas prefab). You will loose the advantage of having a prefab there, the changes won't be applied to this scene.
Fully unpacking the scenePrefab may lead to unwanted behaviors.
For this reason, I think "Prefab -> Unpack" is best.

2022-02-01 23:12 UTC, Maximellerbach commented on docs/guide/create_a_track.md
> +1) In "Assets/Prefabs/" you will find a Prefab called "ScenePrefab". (if not maybe you can find it in Assets/Scenes)
That's right sorry, you can directly change the "Assets/Prefabs/" to "Assets/Scenes", no need for parentheses you are totally right they are now in the Scenes folder !

2022-02-02 07:23 UTC, ebadi commented
Thanks for the comments. I updated the documents accordingly.

2022-02-02 10:21 UTC, Maximellerbach approved these changes
All good ! Merging this, thank you !

2022-02-02 10:21 UTC, merged